name: Import labels
on:
  push:
    paths:
      - '.github/data/labels.json'

jobs:
  labels:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: checkout source files
        uses: actions/checkout@v2

      - name: use node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install deps
        run: npm ci

      - name: import labels
        if: github.ref == 'refs/heads/main'
        run: |
          npx ghlbl -o adarshaacharya -r stargate -t ${{ secrets.GITHUB_TOKEN }} -d
          npx ghlbl -o adarshaacharya -r stargate -t ${{ secrets.GITHUB_TOKEN }} -i .github/data/labels.json